name: AbilityTrader
main: com.vxnick.abilitytrader.AbilityTrader
version: 0.3.0
description: Allows abilities (commands and permissions) to be purchased or rented.
author: vxnick
website: http://github.com/vxnick/abilitytrader
depend: [Vault]

commands:
  ability:
    description: Ability Trader
    usage: /<command> help for a list of commands
    aliases: [ab, at, abt]
    permission: abilitytrader.use
    permission-message: You don't have permission
permissions:
  abilitytrader.use:
    description: Allows use of this command
    default: true
  abilitytrader.admin.reload:
    description: Reload AbilityTrader configuration
    default: op
  abilitytrader.admin.players:
    description: List players with abilities
    default: op
  abilitytrader.admin.remove:
    description: Remove abilities from players
    default: op
  abilitytrader.admin.*:
    description: Administrative commands
    default: op
    children:
      abilitytrader.admin.players: true
      abilitytrader.admin.remove: true
      abilitytrader.admin.reload: true