name: AbilityTrader
main: com.vxnick.abilitytrader.AbilityTrader
version: 0.2.1
description: Allows abilities (commands and permissions) to be purchased or rented.
author: vxnick
website: http://github.com/vxnick/abilitytrader
depend: [Vault]

commands:
  ability:
    description: Ability Trader
    usage: /<command> help for a list of commands
    aliases: abt
    permission: abilitytrader.use
    permission-message: You don't have permission
permissions:
  abilitytrader.use:
    description: Allows use of this command
    default: op
  abilitytrader.admin:
    description: Administrative commands
    default: op